`timescale 1ns/1ps

// File-driven bit-exact Gate-C regression.  Expected beats are generated by
// generate_gate_c_hdl_vectors.py from the independent VTM10 Oracle.
module unified_its_wrapper_numeric_tb;
    parameter string VECTOR_FILE = "unified_gate_c_vectors.txt";

    logic clk = 1'b0;
    always #1 clk = ~clk;
    logic rst_n = 1'b0;
    logic [21:0] it_info = '0;
    logic it_info_vld = 1'b0;
    logic signed [15:0] it_data_in = '0;
    logic [11:0] it_data_addr = '0;
    logic it_data_in_vld = 1'b0;
    logic it_data_end = 1'b0;
    logic it_data_in_req;
    logic it_data_out_req = 1'b0;
    logic [39:0] it_data_out;
    logic it_data_out_vld;
    logic it_done;
    logic protocol_error;

    unified_its_wrapper dut (
        .clk(clk), .rst_n(rst_n),
        .it_info(it_info), .it_info_vld(it_info_vld),
        .it_data_in(it_data_in), .it_data_addr(it_data_addr),
        .it_data_in_vld(it_data_in_vld), .it_data_end(it_data_end),
        .it_data_in_req(it_data_in_req),
        .it_data_out_req(it_data_out_req),
        .it_data_out(it_data_out), .it_data_out_vld(it_data_out_vld),
        .it_done(it_done), .protocol_error(protocol_error)
    );

    task automatic send_info(input logic [21:0] value);
        begin
            @(negedge clk);
            it_info = value;
            it_info_vld = 1'b1;
            @(posedge clk);
            @(negedge clk);
            it_info_vld = 1'b0;
        end
    endtask

    task automatic send_data(input integer address, input integer value,
                             input bit last);
        begin
            while (!it_data_in_req) @(negedge clk);
            it_data_addr = address[11:0];
            it_data_in = value[15:0];
            it_data_in_vld = 1'b1;
            it_data_end = last;
            @(posedge clk);
            @(negedge clk);
            it_data_in_vld = 1'b0;
            it_data_end = 1'b0;
        end
    endtask

    integer vector_fd;
    integer scan_rc;
    integer case_count;
    integer case_index;
    integer input_count;
    integer beat_count;
    integer input_index;
    integer beat_index;
    integer request_cycle;
    integer done_count;
    integer input_addr [0:15];
    integer input_value[0:15];
    logic [39:0] expected_beat[0:1023];
    logic [21:0] case_desc;
    logic [39:0] held_data;
    bit holding;
    bit fire_now;
    bit last_now;

    initial begin
        vector_fd = $fopen(VECTOR_FILE, "r");
        if (vector_fd == 0)
            $fatal(1, "cannot open vector file %s", VECTOR_FILE);
        scan_rc = $fscanf(vector_fd, "%d", case_count);
        if (scan_rc != 1)
            $fatal(1, "invalid vector header");

        repeat (3) @(negedge clk);
        rst_n = 1'b1;

        for (case_index = 0; case_index < case_count;
             case_index = case_index + 1) begin
            scan_rc = $fscanf(vector_fd, "%h %d %d",
                              case_desc, input_count, beat_count);
            if (scan_rc != 3 || input_count > 16 || beat_count > 1024)
                $fatal(1, "invalid case header case=%0d", case_index);
            for (input_index = 0; input_index < input_count;
                 input_index = input_index + 1) begin
                scan_rc = $fscanf(vector_fd, "%d %d",
                                  input_addr[input_index],
                                  input_value[input_index]);
                if (scan_rc != 2)
                    $fatal(1, "invalid input row case=%0d input=%0d",
                           case_index, input_index);
            end
            for (beat_index = 0; beat_index < beat_count;
                 beat_index = beat_index + 1) begin
                scan_rc = $fscanf(vector_fd, "%h", expected_beat[beat_index]);
                if (scan_rc != 1)
                    $fatal(1, "invalid expected row case=%0d beat=%0d",
                           case_index, beat_index);
            end

            send_info(case_desc);
            for (input_index = 0; input_index < input_count;
                 input_index = input_index + 1)
                send_data(input_addr[input_index], input_value[input_index],
                          input_index == input_count - 1);

            beat_index = 0;
            request_cycle = 0;
            done_count = 0;
            holding = 1'b0;
            while (beat_index < beat_count) begin
                @(negedge clk);
                it_data_out_req = ((request_cycle + case_index) % 7 != 2) &&
                                  ((request_cycle + case_index) % 11 != 5);
                request_cycle = request_cycle + 1;
                #0;
                if (!it_data_out_req) begin
                    if (it_data_out_vld)
                        $fatal(1, "out_valid asserted under stall case=%0d",
                               case_index);
                    if (dut.output_active) begin
                        if (holding && it_data_out !== held_data)
                            $fatal(1, "hold changed case=%0d beat=%0d",
                                   case_index, beat_index);
                        held_data = it_data_out;
                        holding = 1'b1;
                    end else begin
                        holding = 1'b0;
                    end
                end else begin
                    holding = 1'b0;
                end

                @(posedge clk);
                fire_now = it_data_out_vld && it_data_out_req;
                last_now = fire_now && (beat_index == beat_count - 1);
                if (it_done !== last_now)
                    $fatal(1,
                           "done/fire mismatch case=%0d beat=%0d done=%0b last=%0b",
                           case_index, beat_index, it_done, last_now);
                if (fire_now) begin
                    if (it_data_out !== expected_beat[beat_index])
                        $fatal(1,
                               "numeric mismatch case=%0d beat=%0d got=%010h expected=%010h",
                               case_index, beat_index, it_data_out,
                               expected_beat[beat_index]);
                    done_count = done_count + it_done;
                    beat_index = beat_index + 1;
                end
                if (protocol_error)
                    $fatal(1, "protocol_error case=%0d", case_index);
            end
            if (done_count != 1)
                $fatal(1, "done count mismatch case=%0d count=%0d",
                       case_index, done_count);
            @(posedge clk);
            if (it_done)
                $fatal(1, "done pulse wider than one edge case=%0d", case_index);
            it_data_out_req = 1'b0;
        end

        $fclose(vector_fd);
        $display("GATE_C_NUMERIC_TB_PASS cases=%0d", case_count);
        $finish;
    end
endmodule
