`timescale 1ns/1ps

// Gate-C protocol smoke bench for unified_its_wrapper.
// The bit-exact numerical vectors are generated by
// validate_gate_c_model.py; this bench focuses on interface timing, two-slot
// ownership, request-gated output valid, hold-under-stall, and one done pulse.

module unified_its_wrapper_tb;
    logic clk = 1'b0;
    always #1 clk = ~clk;
    logic rst_n = 1'b0;
    logic [21:0] it_info = '0;
    logic it_info_vld = 1'b0;
    logic signed [15:0] it_data_in = '0;
    logic [11:0] it_data_addr = '0;
    logic it_data_in_vld = 1'b0;
    logic it_data_end = 1'b0;
    logic it_data_in_req;
    logic it_data_out_req = 1'b0;
    logic [39:0] it_data_out;
    logic it_data_out_vld;
    logic it_done;
    logic protocol_error;

    unified_its_wrapper dut (
        .clk(clk), .rst_n(rst_n),
        .it_info(it_info), .it_info_vld(it_info_vld),
        .it_data_in(it_data_in), .it_data_addr(it_data_addr),
        .it_data_in_vld(it_data_in_vld), .it_data_end(it_data_end),
        .it_data_in_req(it_data_in_req),
        .it_data_out_req(it_data_out_req),
        .it_data_out(it_data_out), .it_data_out_vld(it_data_out_vld),
        .it_done(it_done), .protocol_error(protocol_error)
    );

    function automatic [21:0] desc(input integer w, input integer h,
                                    input integer hor, input integer ver,
                                    input integer set_i, input integer idx_i);
        desc = w[6:0] | (h[6:0] << 7) | (hor[1:0] << 14) |
               (ver[1:0] << 16) | (set_i[1:0] << 18) | (idx_i[1:0] << 20);
    endfunction

    task automatic send_info(input [21:0] value);
        begin
            @(negedge clk);
            it_info <= value;
            it_info_vld <= 1'b1;
            @(posedge clk);
            @(negedge clk);
            it_info_vld <= 1'b0;
        end
    endtask

    task automatic send_data(input integer address, input integer value,
                             input bit last);
        begin
            while (!it_data_in_req) @(negedge clk);
            @(negedge clk);
            it_data_addr <= address[11:0];
            it_data_in <= value[15:0];
            it_data_in_vld <= 1'b1;
            it_data_end <= last;
            @(posedge clk);
            @(negedge clk);
            it_data_in_vld <= 1'b0;
            it_data_end <= 1'b0;
        end
    endtask

    integer first_beats;
    integer second_beats;
    integer first_done;
    integer second_done;
    logic [39:0] held_data;
    bit holding;
    bit finished;
    initial begin
        repeat (3) @(negedge clk);
        rst_n <= 1'b1;

        // TU0: 8x8 DCT2xDCT2, sparse raster input.
        send_info(desc(8, 8, 0, 0, 0, 0));
        send_data(0, 123, 1'b0);
        send_data(63, -77, 1'b1);

        // Queue TU1 before TU0 output is drained.  TU1 uses mixed H/V types
        // and exercises the second ownership slot.
        send_info(desc(16, 4, 2, 1, 0, 0));
        send_data(0, 55, 1'b0);
        send_data(63, -22, 1'b1);

        first_beats = 0;
        second_beats = 0;
        first_done = 0;
        second_done = 0;
        holding = 1'b0;
        finished = 1'b0;
        repeat (20000) begin
            @(negedge clk);
            // Alternate request stalls.  External valid must be low during
            // every stall, while data remains unchanged.
            it_data_out_req <= (($time / 2) % 5 != 1);
            if (!it_data_out_req) begin
                if (it_data_out_vld)
                    $fatal(1, "out_valid asserted while req=0");
                if (holding && it_data_out !== held_data)
                    $fatal(1, "output data changed during stall");
                holding = 1'b1;
            end else if (it_data_out_vld) begin
                held_data = it_data_out;
                holding = 1'b0;
                if (first_beats < 16)
                    first_beats = first_beats + 1;
                else
                    second_beats = second_beats + 1;
            end
            if (it_done) begin
                if (first_done == 0)
                    first_done = 1;
                else
                    second_done = second_done + 1;
            end
            if ((first_done == 1) && (second_done == 1) &&
                (second_beats == 16)) begin
                finished = 1'b1;
                break;
            end
        end
        if (protocol_error)
            $fatal(1, "unexpected protocol_error");
        if (first_beats != 16 || second_beats != 16 ||
            first_done != 1 || second_done != 1)
            $fatal(1, "two-TU output contract failed");
        $display("GATE_C_WRAPPER_TB_PASS beats=%0d/%0d done=%0d/%0d",
                 first_beats, second_beats, first_done, second_done);
        $finish;
    end
endmodule
