"""Generate the B1 DCT2-64 RTL operation/signal tables from the frozen P2F model.

The generated include is data only: lane assignment, source index, coefficient,
dot id, and the exact recursive signal graph.  No transform algorithm is
re-derived in this script.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "03_verification" / "scripts" / "p2f"))

from run_p2f_a1_dataflow import P4Dataflow  # noqa: E402

OUT = ROOT / "02_rtl" / "rtl" / "p2f_b1_tables.svh"
MANIFEST = ROOT / "03_verification" / "output" / "p2f_b1_generated_table_manifest.json"
LANES = 128


def collect_signals(model: P4Dataflow):
    signals = []
    sid_by_obj: dict[int, int] = {}

    def visit(sig):
        if id(sig) in sid_by_obj:
            return sid_by_obj[id(sig)]
        if sig.even is not None:
            visit(sig.even)
        sid = len(signals)
        sid_by_obj[id(sig)] = sid
        signals.append(sig)
        return sid

    root_sids = [visit(sig) for sig in model.root]
    return signals, sid_by_obj, root_sids


def emit_case_function(name: str, cases: list[tuple[int, int]], default: int) -> list[str]:
    lines = [f"function automatic integer {name}(input integer key);", "  begin", "    case (key)"]
    for key, value in cases:
        lines.append(f"      {key}: {name} = {value};")
    lines.extend([f"      default: {name} = {default};", "    endcase", "  end", "endfunction", ""])
    return lines


def main() -> None:
    model = P4Dataflow()
    signals, sid_by_obj, root_sids = collect_signals(model)

    lane_cases: list[tuple[int, int]] = []
    for op in model.ops:
        lane_cases.append((op.issue_rel * LANES + op.physical_lane, op.op_id))
    src_cases = [(op.op_id, op.source_x_index) for op in model.ops]
    coeff_cases = [(op.op_id, op.coefficient) for op in model.ops]
    dot_cases = []
    term_cases = []
    dot_term_count_cases = []
    for dot in model.dots:
        dot_term_count_cases.append((dot.dot_id, len(dot.op_ids)))
        for term_index, op_id in enumerate(dot.op_ids):
            dot_cases.append((op_id, dot.dot_id))
            term_cases.append((op_id, term_index))
    dot_cases.sort()
    term_cases.sort()

    lines = [
        "// AUTO-GENERATED by generate_p2f_b1_rtl.py; do not edit manually.",
        "// Source: P2F P4Dataflow / ExactDCT2Factorizer schedule.",
        f"localparam integer P2F_OP_COUNT = {len(model.ops)};",
        f"localparam integer P2F_DOT_COUNT = {len(model.dots)};",
        f"localparam integer P2F_SIG_COUNT = {len(signals)};",
        "",
    ]
    lines += emit_case_function("p2f_lane_op", lane_cases, -1)
    lines += emit_case_function("p2f_op_src", src_cases, -1)
    lines += emit_case_function("p2f_op_coeff", coeff_cases, 0)
    lines += emit_case_function("p2f_op_dot", dot_cases, -1)
    lines += emit_case_function("p2f_op_term", term_cases, -1)
    lines += emit_case_function("p2f_dot_term_count", dot_term_count_cases, 0)

    sig_even_ref: list[int] = []
    sig_even_dot: list[int] = []
    sig_odd_dot: list[int] = []
    sig_high: list[int] = []
    sig_level: list[int] = []

    def signal_level(sig) -> int:
        if sig.even is None:
            return 1
        return 1 + signal_level(sig.even)

    for sig in signals:
        if sig.even is None:
            sig_even_ref.append(-1)
            sig_even_dot.append(getattr(sig, "even_dot").dot_id)
        else:
            sig_even_ref.append(sid_by_obj[id(sig.even)])
            sig_even_dot.append(-1)
        sig_odd_dot.append(sig.odd.dot_id)
        sig_high.append(int("high" in sig.signal_id))
        sig_level.append(signal_level(sig))

    # Signal graph properties are emitted as constant functions so the RTL
    # can express the exact recursive graph without a hand-maintained map.
    lines += emit_case_function("p2f_sig_even_ref", list(enumerate(sig_even_ref)), -1)
    lines += emit_case_function("p2f_sig_even_dot", list(enumerate(sig_even_dot)), -1)
    lines += emit_case_function("p2f_sig_odd_dot", list(enumerate(sig_odd_dot)), -1)
    lines += emit_case_function("p2f_sig_is_high", list(enumerate(sig_high)), 0)
    lines += emit_case_function("p2f_sig_level", list(enumerate(sig_level)), 0)
    lines += emit_case_function("p2f_root_sig", list(enumerate(root_sids)), -1)

    OUT.write_text("\n".join(lines), encoding="utf-8")
    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(
        json.dumps(
            {
                "source_model": "run_p2f_a1_dataflow.P4Dataflow",
                "operation_count": len(model.ops),
                "dot_count": len(model.dots),
                "signal_count": len(signals),
                "lanes": LANES,
                "generated_include": str(OUT),
                "schedule_counts": {
                    str(c): sum(op.issue_rel == c for op in model.ops)
                    for c in range(16)
                },
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"generated {OUT} ({len(model.ops)} operations, {len(signals)} signals)")


if __name__ == "__main__":
    main()
